from typing import Optional, Any, Dict, List
from pydantic import Field
from llm_studio_agents.AgentBase import AgentsTraceBase
from .book_finder_setup import BookFinderAgentSetup


class BookFinderAgentTrace(AgentsTraceBase, BookFinderAgentSetup):
    """
    Trace class for capturing Book Finder Agent execution details.
    Used by the @AITrace decorator to log execution state, inputs, and outputs.
    """
    
    # Input Fields
    user_query: str = Field(
        default="",
        description="The search query provided by the user.",
        title="User Query",
        displayOnCard=True
    )
    
    session_id: str = Field(
        default="",
        description="Session identifier for tracking user interactions.",
        title="Session ID",
        displayOnCard=True
    )
    
    # Filter Fields
    applied_filters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Filters applied to the search query.",
        title="Applied Filters",
        displayOnCard=True
    )
    
    # Execution State Fields
    total_results_retrieved: int = Field(
        default=0,
        description="Total number of book results retrieved from the database.",
        title="Total Results Retrieved"
    )
    
    results_after_filtering: int = Field(
        default=0,
        description="Number of results after applying semantic similarity and filter thresholds.",
        title="Results After Filtering"
    )
    
    results_displayed: int = Field(
        default=0,
        description="Number of results sent to the LLM for generation.",
        title="Results Displayed"
    )
    
    # LLM Generation Output
    final_response: str = Field(
        default="",
        description="Final natural language response generated by the LLM.",
        title="Final Response",
        displayOnCard=True
    )
    
    # Citation Tracking
    citations_generated: int = Field(
        default=0,
        description="Number of citations successfully extracted from the response.",
        title="Citations Generated"
    )
    
    citations_failed: int = Field(
        default=0,
        description="Number of citation extraction attempts that failed.",
        title="Citations Failed"
    )
    
    # Pagination State
    is_pagination_request: bool = Field(
        default=False,
        description="Whether this request was a 'show more' pagination request.",
        title="Is Pagination Request"
    )
    
    undisplayed_results_count: int = Field(
        default=0,
        description="Number of undisplayed results available for pagination.",
        title="Undisplayed Results Count"
    )
    
    # Performance Metrics
    retrieval_time_ms: Optional[float] = Field(
        default=None,
        description="Time in milliseconds for database retrieval.",
        title="Retrieval Time (ms)"
    )
    
    scoring_time_ms: Optional[float] = Field(
        default=None,
        description="Time in milliseconds for result scoring and ranking.",
        title="Scoring Time (ms)"
    )
    
    llm_generation_time_ms: Optional[float] = Field(
        default=None,
        description="Time in milliseconds for LLM response generation.",
        title="LLM Generation Time (ms)"
    )
    
    total_time_ms: Optional[float] = Field(
        default=None,
        description="Total execution time in milliseconds.",
        title="Total Time (ms)"
    )
    
    # Error Tracking
    error_occurred: bool = Field(
        default=False,
        description="Whether an error occurred during execution.",
        title="Error Occurred"
    )
    
    error_message: Optional[str] = Field(
        default=None,
        description="Error message if an error occurred.",
        title="Error Message"
    )
    
    class Config:
        title = "Book Finder Agent Trace"

